Project_settings/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home_app.urls')),
    path('about/', include('about_app.urls')),
    path('spare_part/', include('spare_part_app.urls')),
    path('service/', include('service_app.urls')),
    path('gallery/', include('gallery_app.urls')),
    path('contact/', include('contact_app.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gallery_app/urls.py
from django.urls import path
from gallery_app.views import *

app_name = 'gallery_app'

urlpatterns = [
    path('',gallery_view, name='gallery_url'),
    path('<slug:name>',gallery_filter, name='gallery_filter')
]

home_app/urls.py
from django.urls import path
from home_app.views import *

app_name = 'home_app'

urlpatterns = [
    path('',home_view, name='home_url')
]

gallery_app/models.py
from django.db import models

# Create your models here.


class Categories(models.Model):
    category_name = models.CharField(max_length=50)

    def __str__(self):
        return f'{self.category_name}'


class Gallery(models.Model):
    category_id = models.ForeignKey('Categories',on_delete=models.CASCADE)
    image = models.ImageField(upload_to='media/Gallery')

    def __str__(self):
        return f'Category | {self.category_id}'

gallery_app/views.py
from django.shortcuts import render, redirect
from gallery_app.models import *
from home_app.models import *


# Create your views here.

def gallery_view(request):
    context = {
        'categories': Categories.objects.all(),
        'filter_image': Gallery.objects.all(),
        'footer_data': Footer.objects.all()
    }
    return render(request, 'gallery.html', context)


def gallery_filter(request, name):
    context = {
        'categories': Categories.objects.all(),
        'filter_image': Gallery.objects.filter(category_id__category_name=name),
        'footer_data': Footer.objects.all()
    }

    return render(request, 'gallery.html', context)

gallery_app/templates/gallery.html
{% extends 'base.html' %}
{% load  static %}
{% block title %}<title>Gallery</title>{% endblock %}
{% block content %}
    <section class="page_breadcrumbs cs background_cover section_padding_top_40 section_padding_bottom_40">
				<div class="container">
					<div class="row">
						<div class="col-sm-12 text-center">
							<h2>Qaleriya</h2>
							<ol class="breadcrumb">
								<li>
									<a href="{% url 'home_app:home_url' %}">
										Ana Səhifə
									</a>
								</li>
								<li class="active">Qaleriya</li>
							</ol>
						</div>
					</div>
				</div>
			</section>

			<section class="ls page_portfolio section_padding_top_100 section_padding_bottom_100">
				<div class="container">
					<div class="row">
						<div class="col-sm-12">
							<div class="filters text-center">
								<a href="{% url 'gallery_app:gallery_url' %}" class="selected">Hamısı</a>
                                {% for c in categories %}
								<a href="{% url 'gallery_app:gallery_filter' name=c.category_name %}">{{c.category_name }}</a>
								{% endfor %}
							</div>
							<div class="isotope_container isotope row masonry-layout columns_margin_top_0 columns_margin_bottom_30">
                                {% for i in filter_image %}
								<div class="isotope-item col-lg-6 col-md-6 col-sm-12">
									<div
										class="vertical-item content-padding gallery-extended-item with_border text-center">
										<div class="item-media">
											<img src="{{ i.image.url }}" alt="">
											<div class="media-links">
											</div>
										</div>
									</div>
								</div>
                                {% endfor %}
							</div>
							<div class="row topmargin_20">
								<div class="col-sm-12 text-center">
									<img src="{% static 'project_static/img/loading.png' %}" alt="" class="fa-spin" />
								</div>
							</div>
						</div>
					</div>
				</div>
			</section>
{% endblock %}