Project_settings/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home_app.urls')),
    path('about/', include('about_app.urls')),
    path('spare_part/', include('spare_part_app.urls')),
    path('service/', include('service_app.urls')),
    path('gallery/', include('gallery_app.urls')),
    path('contact/', include('contact_app.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

about_app/urls.py
from django.urls import path
from about_app.views import *

app_name = 'about_app'

urlpatterns = [
    path('',about_view, name='about_url')
]

contact_app/urls.py
from django.urls import path
from contact_app.views import *

app_name = 'contact_app'

urlpatterns = [
    path('',contact_view, name='contact_url')
]

gallery_app/urls.py
from django.urls import path
from gallery_app.views import *

app_name = 'gallery_app'

urlpatterns = [
    path('',gallery_view, name='gallery_url'),
    path('<slug:name>',gallery_filter, name='gallery_filter')
]

home_app/urls.py
from django.urls import path
from home_app.views import *

app_name = 'home_app'

urlpatterns = [
    path('',home_view, name='home_url')
]

service_app/urls.py
from django.urls import path
from service_app.views import *

app_name = 'service_app'

urlpatterns = [
    path('',service_view, name='service_url')
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html class="no-js">

<head>
	<meta charset="utf-8">
	<meta name="description" content="">
    {% block title %}<title>Not Found</title>{% endblock %}
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'project_static/images/icons/ag-logo.png' %}" />
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="{% static 'project_static/css/bootstrap.min.css' %}">
	<link rel="stylesheet" href="{% static 'project_static/css/animations.css' %}">
	<link rel="stylesheet" href="{% static 'project_static/css/fonts.css' %}">
	<link rel="stylesheet" href="{% static 'project_static/css/main.css' %}" id="color-switcher-link">
	<script src="{% static 'project_static/js/vendor/modernizr-2.6.2.min.js' %}"></script>
</head>

<body>
<div class="preloader">
		<div class="preloader_image"></div>
	</div>
	<div id="canvas">
        <header class="page_header header_darkgrey header_logo_center toggler_right menu_justify">
				<div class="container-fluid">
					<div class="row">
						<div class="col-sm-12 text-left text-md-center">
							<div class="logo_wrapper">
								<a href="{% url 'home_app:home_url' %}" class="logo">
									<img src="{% static 'project_static/images/icons/ag-logo.png' %}" alt="#">
								</a>
							</div>
							<span class="toggle_menu">
								<span></span>
							</span>
							<nav class="mainmenu_wrapper">
								<ul class="mainmenu nav sf-menu">
									<li>
										<a href="{% url 'about_app:about_url' %}">Haqqında</a>
									</li>
									<li>
										<a>Xidmətlərimiz</a>
										<ul>
											<li>
												<a href="{% url 'spare_part_app:spare_part_url' %}">Ehtiyat hissələri</a>
											</li>
											<li>
												<a href="{% url 'service_app:service_url' %}">Servis xidməti</a>
											</li>
											<li>

											</li>
										</ul>
									</li>
									<li>
										<a href="{% url 'gallery_app:gallery_url' %}">Qaleriya</a>
									</li>
									<li>
										<a href="{% url 'contact_app:contact_url' %}">Əlaqə</a>
									</li>
								</ul>
							</nav>
						</div>
					</div>
				</div>
			</header>

        {% block content %}{% endblock %}

        <footer class="page_footer ds section_padding_top_65 section_padding_bottom_50 columns_margin_bottom_40">
				<div class="container">
					<div class="row">
						<div class="col-md-3 col-sm-6 to_animate" data-animation="fadeInUp">
							<a href="{% url 'home_app:home_url' %}" class="logo">
								<img src="{% static 'project_static/images/icons/ag-logo.png' %}" alt="#">
							</a>
							<p>
								{{ footer_data.0.text }}
							</p>
							<p>
								<a href="{{ footer_data.0.instagram_link }}" class="social-icon theme-color-icon soc-instagram"></a>
								<a href="{{ footer_data.0.facebook_link }}" class="social-icon theme-color-icon soc-facebook"></a>

							</p>
						</div>
						<div class="col-md-3 col-sm-6 to_animate" data-animation="fadeInUp">
							<div class="topmargin_15 columns_margin_0">
								<div class="widget widget_pages">
									<h3 class="widget-title">Faydalı
										<strong>Linklər</strong>
									</h3>
									<hr class="divider_30_3 zebra_bg divider_left">
									<div class="row columns_padding_0 columns_margin_0">
										<div class="col-xs-6">
											<ul class="greylinks">
												<li>
													<a href="{% url 'about_app:about_url' %}">Haqqında</a>
												</li>
												<li>
													<a href="{% url 'service_app:service_url' %}">Servis xidmətləri</a>
												</li>
												<li>
													<a href="{% url 'gallery_app:gallery_url' %}">Qaleriya</a>
												</li>
											</ul>
										</div>
										<div class="col-xs-6">
											<ul class="greylinks">
												<li>
													<a href="{% url 'spare_part_app:spare_part_url' %}">Ehtiyyat hissələri</a>
												</li>
												<li>
													<a href="{% url 'contact_app:contact_url' %}">Əlaqə</a>
												</li>
											</ul>
										</div>
									</div>
								</div>
							</div>
						</div>
						<div class="col-md-3 col-sm-6 to_animate" data-animation="fadeInUp">
							<div class="widget widget_text topmargin_15">
								<h3 class="widget-title">ƏLAQƏDƏ
									<strong>OLMAQ</strong>
								</h3>
								<hr class="divider_30_3 zebra_bg divider_left">
								<div class="media small-teaser">
									<div class="media-left">
										<i class="fa fa-map-marker highlight fontsize_18"></i>
									</div>
									<div class="media-body">
										{{ footer_data.0.my_location }}
									</div>
								</div>
								<div class="media small-teaser">
									<div class="media-left">
										<i class="fa fa-envelope highlight fontsize_18"></i>
									</div>
									<div class="media-body greylinks">
										<a href="mailto:example@example.com">{{ footer_data.0.email }}</a>
									</div>
								</div>
								<div class="media small-teaser">
									<div class="media-left">
										<i class="fa fa-phone highlight fontsize_18"></i>
									</div>
									<div class="media-body">
										{{ footer_data.0.phone_number }}
									</div>
								</div>
                                <div class="media small-teaser">
									<div class="media-left">
										<i class="fa fa-whatsapp highlight fontsize_18"></i>
									</div>
									<div class="media-body">
										{{ footer_data.0.whatsapp_number }}
									</div>
								</div>
								<div class="media small-teaser">
									<div class="media-left">
										<i class="fa fa-clock-o highlight fontsize_18"></i>
									</div>
									<div class="media-body">
										{{ footer_data.0.time_text }}
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</footer>
    </div>

	<script src="{% static 'project_static/js/compressed.js' %}"></script>
	<script src="{% static 'project_static/js/main.js' %}"></script>
    {% block js %}{% endblock %}
</body>

</html>