Project_settings/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home_app.urls')),
    path('about/', include('about_app.urls')),
    path('spare_part/', include('spare_part_app.urls')),
    path('service/', include('service_app.urls')),
    path('gallery/', include('gallery_app.urls')),
    path('contact/', include('contact_app.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home_app/urls.py
from django.urls import path
from home_app.views import *

app_name = 'home_app'

urlpatterns = [
    path('',home_view, name='home_url')
]

spare_part_app/urls.py
from django.urls import path
from spare_part_app.views import *

app_name = 'spare_part_app'

urlpatterns = [
    path('',spare_part_view, name='spare_part_url'),
    path('<slug:name>',spare_part_filter_view, name='spare_part_filter_view'),
    path('spare_part_detail/<slug:category_name>/<slug:product_id>/',spare_part_detail_view, name='spare_part_detail_url'),
]

spare_part_app/models.py
from django.db import models
# from mptt.models import MPTTModel, TreeForeignKey

# Create your models here.


class Categories(models.Model):
    category_name = models.CharField(max_length=50)

    def __str__(self):
        return f'{self.category_name}'


class Products(models.Model):
    category_id = models.ForeignKey('Categories', on_delete=models.CASCADE)
    product_name = models.CharField(max_length=100)
    product_description = models.CharField(max_length=255)
    image = models.ImageField(blank=True)
    price = models.CharField(max_length=20, null=True, blank=True)
    about_product = models.TextField()

    def __str__(self):
        return f'Category | {self.category_id}'


class ProductImages(models.Model):
    product_id = models.ForeignKey('Products',default=None, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='media/ProductIMages')

    def __str__(self):
        return f'{self.product_id}'

spare_part_app/views.py
from django.shortcuts import render
from spare_part_app.models import Categories, Products, ProductImages
from home_app.models import Footer


# Create your views here.
def spare_part_view(request):
    context = {
        'categories': Categories.objects.all(),
        'product_list': Products.objects.all(),
        'footer_data': Footer.objects.all()
    }
    return render(request, 'spare_part.html', context)


def spare_part_filter_view(request, name):
    context = {
        'categories': Categories.objects.all(),
        'product_list': Products.objects.filter(category_id__category_name=name),
        'footer_data': Footer.objects.all()
    }

    return render(request, 'spare_part.html', context)


def spare_part_detail_view(request,category_name,product_id):
    context = {
        'product_detail': Products.objects.filter(category_id__category_name=category_name, id=product_id),
        'product_images': ProductImages.objects.filter(product_id__category_id__category_name=category_name, product_id=product_id),
        'footer_data': Footer.objects.all()
    }

    return render(request, 'spare_part_detail.html',context)

spare_part_app/templates/spare_part.html
{% extends 'base.html' %}
{% load static %}
{% block title %}<title>Spare Parts</title>{% endblock %}
{% block content %}
	<section class="page_breadcrumbs cs background_cover section_padding_top_40 section_padding_bottom_40">
				<div class="container">
					<div class="row">
						<div class="col-sm-12 text-center">
							<h2>Ehtiyat hissələri</h2>
							<ol class="breadcrumb">
								<li>
									<a href="{% url 'spare_part_app:spare_part_url' %}">
										Ana Səhifə
									</a>
								</li>
								<li class="active">Ehtiyat hissələri</li>
							</ol>
						</div>
					</div>
				</div>
			</section>

			<section class="ls page_portfolio section_padding_top_100 section_padding_bottom_100">
				<div class="container">
					<div class="row">
						<div class="col-sm-12">
							<div class="filters text-center">
								<a href="{% url 'spare_part_app:spare_part_url' %}" class="selected">Hamısı</a>
                                {% for c in categories %}
								<a href="{% url 'spare_part_app:spare_part_filter_view' name=c.category_name %}">{{c.category_name }}</a>
								{% endfor %}
							</div>
							<div class="isotope_container isotope row masonry-layout columns_margin_top_0 columns_margin_bottom_30">
                                {% for s in product_list %}
								<a href="{% url 'spare_part_app:spare_part_detail_url' category_name=s.category_id product_id=s.id %}" class="isotope-item col-lg-6 col-md-6 col-sm-12 bmw_door">
									<div
										class="vertical-item content-padding gallery-extended-item with_border text-center">
										<div class="item-media">
											<img src="{{ s.image.url }}" alt="">
											<div class="media-links">
												<div class="abs-link overlay_price">
													<span class="price">Qiymət: </span>
													<h3 class="price">{{ s.price }}</h3>
												</div>
											</div>
										</div>
										<div class="item-content top-zebra-border product_item">
											<h3 class="title">{{ s.product_name }}</h3>
											<p>Categories: <span>{{ s.category_id }}</span></p>
											<p class="content">{{ s.about_product }}</p>
										</div>
									</div>
								</a>
							    {% endfor %}
                            </div>
							<div class="row topmargin_20">
								<div class="col-sm-12 text-center">
									<img src="{% static 'project_static/img/loading.png' %}" alt="" class="fa-spin" />
								</div>
							</div>

						</div>
					</div>
				</div>
			</section>
{% endblock %}

spare_part_app/templates/spare_part_detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}<title>Spare Parts Detail</title>{% endblock %}
{% block content %}
         <section class="page_breadcrumbs cs background_cover section_padding_top_40 section_padding_bottom_40">
                <div class="container">
                    <div class="row">
                        <div class="col-sm-12 text-center">
                            <h2>Ətraflı</h2>
                            <ol class="breadcrumb">
                                <li>
                                    <a href="{% url 'home_app:home_url' %}">
                                        Ana Səhifə
                                    </a>
                                </li>
                                <li>
                                    <a href="{% url 'spare_part_app:spare_part_url' %}">
                                        Ehtiyat hissələri
                                    </a>
                                </li>
                                <li class="active">Ehtiyyat hissələri ətraflı</li>
                            </ol>
                        </div>
                    </div>
                </div>
            </section>

            <section class="detail_product ls section_padding_top_100 section_padding_bottom_75">
                <div class="container">
                    <div class="info_block">
                        <div class="left-container">
                            <div class="product-image--container">
                                <img class="product-image--featured" id="featured"
                                    src="{{ product_detail.0.image.url }}" alt="toaster" />
                                <div class="owl-slider">
                                    <div id="carousel_product" class="owl-carousel product-image--list">
                                        <div class="item item-selected">
                                            <img class="owl-lazy"
                                                data-src="{{ product_detail.0.image.url }}"
                                                alt="">
                                        </div>
                                        {% for p in product_images %}
                                        <div class="item">
                                            <img class="owl-lazy"
                                                data-src="{{ p.image.url }}"
                                                alt="">
                                        </div>
                                        {% endfor %}
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="right-container">
                            <div>
                                <h1 class="title">{{ product_detail.0.product_name }}</h1>
                                <h2 class="subtitle subtitle-container">{{ product_detail.0.category_id }}</h2>
                            </div>
                            <span>
                                <p>Qiymət:
                                    <span class="emphasize">{{ product_detail.0.price }}</span>
                                </p>
                            </span>
                            <div>
                                <h2 class="title">{{ product_detail.0.product_description }}</h2>
                                <div class="subtitle-container">
{#                                    <span>Size: 1-Pack</span>#}
{#                                    <span>|</span>#}
{#                                    <span>Color: Black</span>#}
                                </div>
                                <p>
                                    {{ product_detail.0.about_product }}
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
{% endblock %}